### PR TITLE
Capitalize Arduino.h

### PR DESCRIPTION
**Pull request by Riyyi**
Fixes issue with PlatformIO. #4

### CODE REVIEW

**Comment by teeffelen** [comment]
+1

**Comment by teeuwen** [comment]
It is of utmost urgency that this is merged asap. This issue is preventing myself and other students from using this library. 😠

**Comment by shardpelt** [comment]
+2

**Comment by Jortst** [comment]
+3. This is very important.

**Comment by MarcoMaissan** [comment]
+4

**Comment by StephanK00** [comment]
+5

**Comment by JdeH** [comment]
Dank voor 't PR!

**Pull request merged**
